version: '3.1'
services:
  postgresdb:
    container_name: order-management-db
    hostname: postgres
    image: postgres:16.1
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=pfmbackend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
